### ISSUE TITLE
Comments on non-Redux implementation

### ISSUE THREAD

**Issue by liaujianjie** [wallacelim97/learn-redux#2]
### Good

* Looks visually okay
* Use of spread syntax
* Use of basic CSS
* Use of `styled-components` (third-party library)

### Breaking

* Missing dependency `react-router-dom`

### Concept violation

* You should be using another `useState` to store the state of your textfield. Then, your `handleAdd(...)` function should use that state instead of extracting the value from the DOM. In React, you almost never have to access the DOM directly. Especially for basic use cases such as this. Getting data from the DOM like your did with `document.getElementById` is a violation fundamental React concepts. Check the [docs](https://reactjs.org/docs/handling-events.html) on how you should be up.
* You should not be storing states in your DOM element like how you're using the `name` attribute to contain the index of the item.

### Possible improvements & things to think about

* Use `const` instead of `let` whenever possible. How are they different? What about `var`?
* Is it a good idea to use index for your keys when mapping arrays to components? Why?
* Split components into multiple files.
* Use moment.js or other similar libraries to format dates.
* Save the frequently-used values you're using (e.g. the colors in your CSS) into a constant variable instead of copy-pasting these values everywhere.
* Delete unused files. Keep things clean.
* Use a code formatter like Prettier.
* You can refer to [this repo](https://github.com/liaujianjie/workshop-example-todo) to see how I'd have done things differently.

**Comment by wallacelim97** [comment]
### Breaking

* Missing dependency `react-router-dom` (:heavy_check_mark:)

### Concept violation

* You should be using another `useState` to store the state of your textfield. Then, your `handleAdd(...)` function should use that state instead of extracting the value from the DOM. In React, you almost never have to access the DOM directly. Especially for basic use cases such as this. Getting data from the DOM like your did with `document.getElementById` is a violation fundamental React concepts. Check the [docs](https://reactjs.org/docs/handling-events.html) on how you should be up. (:heavy_check_mark:)
* You should not be storing states in your DOM element like how you're using the `name` attribute to contain the index of the item. (:heavy_check_mark:)

### Possible improvements & things to think about

* Use `const` instead of `let` whenever possible. How are they different? What about `var`?

   Similarities: 
   - block scoped
   - hoisted to top of scope
   - cannot be redeclared

   Differences: 
   - `const` must be initialised on declaration
   - `const` cannot be updated

   Therefore `const` is an even 'safer' option than `let` wherever both are applicable.

* Is it a good idea to use index for your keys when mapping arrays to components? Why?

   On further research I realise this is not a good idea for **mutable** lists, such as that in this app. React 
   uses keys to uniquely identify DOM elements. Indexes can change when the underlying list is mutated, 
   which may cause React to associate stale keys with the wrong DOM element, potentially messing up 
   component state.

* Split components into multiple files. (:heavy_check_mark:)
* Use moment.js or other similar libraries to format dates. (:heavy_check_mark:)
* Save the frequently-used values you're using (e.g. the colors in your CSS) into a constant variable instead of copy-pasting these values everywhere. (:heavy_check_mark:)
* Delete unused files. Keep things clean. (:heavy_check_mark:)
* Use a code formatter like Prettier. (:heavy_check_mark:)
* You can refer to [this repo](https://github.com/liaujianjie/workshop-example-todo) to see how I'd have done things differently.

**Comment by liaujianjie** [comment]
I'm a bit busy these days so I'm gonna have to take a look at this maybe 1-2 weeks from now

**Comment by liaujianjie** [comment]
Hey @wallacelim !

**Comment by liaujianjie** [comment]
Hey @wallacelim !

**Comment by liaujianjie** [comment]
> Hey @wallacelim !

Test comment features 😁

**Comment by wallacelim** [comment]
✅  
**All tests have passed**
2 successful checks

**Comment by liaujianjie** [comment]
> Hey @wallacelim !

Test
